version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        NEXT_PUBLIC_API_URL: http://localhost:8000
        NEXT_PUBLIC_DOMAIN: localhost
        NEXT_PUBLIC_PORT: 8000
    network_mode: host
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ../../values:/app/helm-values
      - ../../scripts:/app/scripts
      - ${KUBECONFIG_PATH:-~/.kube/config}:/root/.kube/config:ro
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - PROMETHEUS_URL=http://prometheus.lavapro.xyz:80
      - TENANT_ID=default
      - IS_SEND_METRICS_TO_S3=false
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=password
      - CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000","http://0.0.0.0:3000"]
    extra_hosts:
      - "prometheus.lavapro.xyz:127.0.0.1"
      - "grafana.lavapro.xyz:127.0.0.1"
    network_mode: host
    restart: unless-stopped
