version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        NEXT_PUBLIC_API_URL: https://dashboard-api.lavapro.xyz:8443
        NEXT_PUBLIC_DOMAIN: lavapro.xyz
        NEXT_PUBLIC_PORT: 443
    network_mode: host
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ../../values:/app/helm-values
      - ../../scripts:/app/scripts
      - ${KUBECONFIG_PATH:-~/.kube/config}:/root/.kube/config:ro
    environment:
      - DEBUG=false
      - LOG_LEVEL=DEBUG
      - PROMETHEUS_URL=http://prometheus.lavapro.xyz:80
      - TENANT_ID=default
      - IS_SEND_METRICS_TO_S3=true
      - S3_BUCKET=smart-router-output-metrics
      - S3_ACCESS_KEY=AKIAXWVQLKJZSRZJG4WJ
      - S3_SECRET_KEY=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
      - S3_REGION=us-east-1
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=password
      - CORS_ORIGINS=["https://dashboard.lavapro.xyz:8443","https://dashboard-api.lavapro.xyz:8443"]
    extra_hosts:
      - "prometheus.lavapro.xyz:127.0.0.1"
      - "grafana.lavapro.xyz:127.0.0.1"
    network_mode: host
    restart: unless-stopped
