import {
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  Moon,
  Sun,
  Laptop,
  Settings,
  LogOut,
  User,
  Home,
  BarChart,
  LineChart,
  PieChart,
  AlertCircle,
  Bell,
  Search,
  Plus,
  Minus,
  RefreshCw,
  Trash2,
  Edit2,
  Save,
  Download,
  Upload,
  Filter,
  MoreVertical,
  ExternalLink,
  ArrowLeft,
  ArrowRight,
  Check,
  XCircle,
  Info,
  HelpCircle,
  Shield,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Mail,
  Phone,
  MessageSquare,
  Calendar,
  Clock,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Share2,
  Copy,
  Link,
  Image,
  File,
  Folder,
  Database,
  Server,
  Network,
  Cloud,
  Wifi,
  Bluetooth,
  Battery,
  Power,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Video,
  VideoOff,
  Camera,
  CameraOff,
  Map,
  MapPin,
  Navigation,
  Compass,
  Globe,
  Flag,
  Tag,
  Hash,
  AtSign,
  DollarSign,
  CreditCard,
  ShoppingCart,
  Package,
  Truck,
  Box,
  Layers,
  Grid,
  List,
  Columns,
  Layout,
  Sidebar,
  Maximize2,
  Minimize2,
  Move,
  RotateCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Crop,
  Scissors,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Code,
  Terminal,
  Command,
  Keyboard,
  MousePointer,
  Touchpad,
  Monitor,
  Smartphone,
  Tablet,
  Watch,
  Headphones,
  Speaker,
  Printer,
  HardDrive,
  Cpu,
  Fan,
  Thermometer,
  Droplet,
  Wind,
  Umbrella,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudSun,
  CloudMoon,
  Sunrise,
  Sunset,
  Server as Logo,
} from 'lucide-react';

export const Icons = {
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  moon: Moon,
  sun: Sun,
  laptop: Laptop,
  settings: Settings,
  logout: LogOut,
  user: User,
  home: Home,
  barChart: BarChart,
  lineChart: LineChart,
  pieChart: PieChart,
  alert: AlertCircle,
  bell: Bell,
  search: Search,
  plus: Plus,
  minus: Minus,
  refresh: RefreshCw,
  trash: Trash2,
  edit: Edit2,
  save: Save,
  download: Download,
  upload: Upload,
  filter: Filter,
  more: MoreVertical,
  external: ExternalLink,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  check: Check,
  xCircle: XCircle,
  info: Info,
  help: HelpCircle,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  phone: Phone,
  message: MessageSquare,
  calendar: Calendar,
  clock: Clock,
  star: Star,
  heart: Heart,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  share: Share2,
  copy: Copy,
  link: Link,
  image: Image,
  file: File,
  folder: Folder,
  database: Database,
  server: Server,
  network: Network,
  cloud: Cloud,
  wifi: Wifi,
  bluetooth: Bluetooth,
  battery: Battery,
  power: Power,
  volume: Volume2,
  volumeOff: VolumeX,
  mic: Mic,
  micOff: MicOff,
  video: Video,
  videoOff: VideoOff,
  camera: Camera,
  cameraOff: CameraOff,
  map: Map,
  mapPin: MapPin,
  navigation: Navigation,
  compass: Compass,
  globe: Globe,
  flag: Flag,
  tag: Tag,
  hash: Hash,
  at: AtSign,
  dollar: DollarSign,
  creditCard: CreditCard,
  shoppingCart: ShoppingCart,
  package: Package,
  truck: Truck,
  box: Box,
  layers: Layers,
  grid: Grid,
  list: List,
  columns: Columns,
  layout: Layout,
  sidebar: Sidebar,
  maximize: Maximize2,
  minimize: Minimize2,
  move: Move,
  rotateCw: RotateCw,
  rotateCcw: RotateCcw,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  crop: Crop,
  scissors: Scissors,
  type: Type,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  code: Code,
  terminal: Terminal,
  command: Command,
  keyboard: Keyboard,
  mouse: MousePointer,
  touchpad: Touchpad,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  watch: Watch,
  headphones: Headphones,
  speaker: Speaker,
  printer: Printer,
  hardDrive: HardDrive,
  cpu: Cpu,
  fan: Fan,
  thermometer: Thermometer,
  droplet: Droplet,
  wind: Wind,
  umbrella: Umbrella,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudLightning: CloudLightning,
  cloudDrizzle: CloudDrizzle,
  cloudFog: CloudFog,
  cloudHail: CloudHail,
  cloudSun: CloudSun,
  cloudMoon: CloudMoon,
  sunrise: Sunrise,
  sunset: Sunset,
  logo: Logo,
};
