import chainNames from "./chain-names.generated.json";

/**
 * Chain metadata keyed by Lava spec index (the `spec` Prometheus label:
 * `ETH1`, `BASE`, `LAVA`, …) — NOT a human chain id. All metric series carry
 * `spec`, so the dashboard resolves display metadata via this map.
 *
 * Names come from `chain-names.generated.json` — the display name from each
 * lava-specs `name` field (126 chains), regenerated by the try-me catalog
 * script. Brand COLORS aren't in the specs, so they stay a small hand-kept
 * overlay here; a chain with a name but no color gets the neutral fallback.
 */
export interface ChainMeta {
  /** The Lava spec index — the `spec` label value. */
  spec: string;
  name: string;
  color: string;
  icon?: string;
}

/** Generated spec-index → display name (all lava-specs chains). */
const NAMES = chainNames as Record<string, string>;

/** Brand colors — the one thing the specs don't carry. Keyed by spec index. */
const COLORS: Record<string, string> = {
  ETH1: "#627EEA",
  BASE: "#0052FF",
  ARBITRUM: "#28A0F0",
  POLYGON: "#8247E5",
  OPTM: "#FF0420",
  LAVA: "#FF3900",
  COSMOSHUB: "#2E3148",
  SOLANA: "#14F195",
  BTC: "#F7931A",
  HYPERLIQUID: "#97FCE4",
  APT1: "#06F7C7",
};

const FALLBACK_COLOR = "#6B7280";

/**
 * Resolve display metadata for a `spec` label. Name comes from the generated
 * lava-specs map (falling back to the raw index for a truly unknown spec);
 * color from the brand overlay (neutral gray otherwise).
 */
export function buildChainMetaByIndex(spec: string): ChainMeta {
  return {
    spec,
    name: NAMES[spec] ?? spec,
    color: COLORS[spec] ?? FALLBACK_COLOR,
  };
}

/** Every chain the specs define, as ChainMeta — for lists/pickers. */
export const KNOWN_CHAINS: ChainMeta[] = Object.keys(NAMES).map(
  buildChainMetaByIndex,
);
