export interface Chain {
  value: string;
  label: string;
  icon: string;
  type: string;
  supportedInterfaces: string[];
  hasWss?: boolean;
}

export const chains: Chain[] = [
  {
    value: 'arbitrum',
    label: 'Arbitrum Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/arbitrum-one.svg',
    type: 'evm-arbitrum',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'arbitrumn',
    label: 'Arbitrum Nova',
    icon: 'https://info-mainnet.lavanet.xyz/chains/arbitrum-nova.svg',
    type: 'evm-arbitrum',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'arbitrums',
    label: 'Arbitrum Sepolia Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/arbitrum-nova.svg',
    type: 'evm-arbitrum',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'avax',
    label: 'Avalanche Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/avalanche.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'avaxt',
    label: 'Avalanche Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/avalanche.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'avalanchec',
    label: 'Avalanche C-Chain Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/avalanche.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'avalanchect',
    label: 'Avalanche C-Chain Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/avalanche.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'avalanchep',
    label: 'Avalanche P-Chain Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/avalanche.svg',
    type: 'avalanchep',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'avalanchept',
    label: 'Avalanche P-Chain Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/avalanche.svg',
    type: 'avalanchep',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'axelar',
    label: 'Axelar Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/axelar.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'axelart',
    label: 'Axelar Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/axelar.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'base',
    label: 'Base Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/base.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'bases',
    label: 'Base Sepolia',
    icon: 'https://info-mainnet.lavanet.xyz/chains/base.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'blast',
    label: 'Blast Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/blast.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'blastsp',
    label: 'Blast Sepolia',
    icon: 'https://info-mainnet.lavanet.xyz/chains/blast.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'bsc',
    label: 'Binance Smart Chain Mainnet',
    icon: 'https://info.lavanet.xyz/chains/binance-smart-chain.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'bsct',
    label: 'Binance Smart Chain Testnet',
    icon: 'https://info.lavanet.xyz/chains/binance-smart-chain.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'cardano',
    label: 'Cardano Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/cardano.svg',
    type: 'cardano',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'cardanot',
    label: 'Cardano Preprod Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/cardano.svg',
    type: 'cardano',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'casper',
    label: 'Casper Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/casper.svg',
    type: 'casper',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'caspert',
    label: 'Casper Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/casper.svg',
    type: 'casper',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'celo',
    label: 'Celo Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/celo.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'alfajores',
    label: 'Celo Alfajores',
    icon: 'https://info-mainnet.lavanet.xyz/chains/celo.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'cosmoshub',
    label: 'Cosmos Hub Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/cosmos-hub.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'cosmoshubt',
    label: 'Cosmos Hub Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/cosmos-hub.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'eth1',
    label: 'Ethereum Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/ethereum.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'sep1',
    label: 'Ethereum Sepolia',
    icon: 'https://info-mainnet.lavanet.xyz/chains/ethereum.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'hol1',
    label: 'Ethereum Holesky',
    icon: 'https://info-mainnet.lavanet.xyz/chains/ethereum.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'hyperliquid',
    label: 'Hyperliquid Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/HL-green.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'hyperliquidt',
    label: 'Hyperliquid Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/HL-green.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'hedera',
    label: 'Hedera Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/hedera.svg',
    type: 'hedera',
    supportedInterfaces: ['jsonrpc', 'rest'],
  },
  {
    value: 'iota',
    label: 'IOTA Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/iota.svg',
    type: 'iota',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'iotat',
    label: 'IOTA Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/iota.svg',
    type: 'iota',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'evmos',
    label: 'Evmos Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/evmos.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'jsonrpc', 'grpc'],
  },
  {
    value: 'evmost',
    label: 'Evmos Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/evmos.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'jsonrpc', 'grpc'],
  },
  {
    value: 'ftm250',
    label: 'Fantom Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/fantom.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'ftm4002',
    label: 'Fantom Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/fantom.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'fuse',
    label: 'Fuse Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/fuse.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'spark',
    label: 'Fuse Spark',
    icon: 'https://info-mainnet.lavanet.xyz/chains/fuse.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'fvm',
    label: 'Filecoin Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/filecoin.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'fvmt',
    label: 'Filecoin Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/filecoin.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'lava',
    label: 'Lava Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/lava.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'lav1',
    label: 'Lava Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/lava.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'monad',
    label: 'Monad Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/monad.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'monadt',
    label: 'Monad Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/monad.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'movement',
    label: 'Movement Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/movement.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'movementt',
    label: 'Movement Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/movement.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'near',
    label: 'NEAR Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/near.svg',
    type: 'near',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'neart',
    label: 'NEAR Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/near.svg',
    type: 'near',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'optm',
    label: 'Optimism Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/optimism.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'optms',
    label: 'Optimism Sepolia',
    icon: 'https://info-mainnet.lavanet.xyz/chains/optimism.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'polygon',
    label: 'Polygon Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/polygon-pos.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'polygona',
    label: 'Polygon Amoy',
    icon: 'https://info-mainnet.lavanet.xyz/chains/polygon-pos.svg',
    type: 'evm',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'polkadotassethub',
    label: 'Polkadot Asset Hub Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/polkadot.svg',
    type: 'polkadotassethub',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'polkadotassethubt',
    label: 'Polkadot Asset Hub Westend Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/polkadot.svg',
    type: 'polkadotassethub',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'solana',
    label: 'Solana Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/solana.svg',
    type: 'solana',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'solanat',
    label: 'Solana Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/solana.svg',
    type: 'solana',
    supportedInterfaces: ['jsonrpc'],
    hasWss: true,
  },
  {
    value: 'strgz',
    label: 'Stargaze Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/stargaze.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'strgzt',
    label: 'Stargaze Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/stargaze.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'strk',
    label: 'Starknet Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/starknet.svg',
    type: 'starknet',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'strks',
    label: 'Starknet Sepolia',
    icon: 'https://info-mainnet.lavanet.xyz/chains/starknet.svg',
    type: 'starknet',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'tezos',
    label: 'Tezos Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/tezos.svg',
    type: 'tezos',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'tezost',
    label: 'Tezos Shadownet Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/tezos.svg',
    type: 'tezos',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'ton',
    label: 'TON Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/ton.svg',
    type: 'ton',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'tont',
    label: 'TON Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/ton.svg',
    type: 'ton',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'trx',
    label: 'TRON Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/tron.svg',
    type: 'tron',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'trxt',
    label: 'TRON Shasta Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/tron.svg',
    type: 'tron',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'union',
    label: 'Union Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/union.svg',
    type: 'cosmos',
    supportedInterfaces: ['rest', 'tendermintrpc', 'grpc'],
  },
  {
    value: 'xlm',
    label: 'Stellar Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/stellar.svg',
    type: 'xlm',
    supportedInterfaces: ['rest', 'jsonrpc'],
  },
  {
    value: 'xlmt',
    label: 'Stellar Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/stellar.svg',
    type: 'xlm',
    supportedInterfaces: ['rest', 'jsonrpc'],
  },
  {
    value: 'xrp',
    label: 'XRP Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/xrp.svg',
    type: 'xrp',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'xrpt',
    label: 'XRP Testnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/xrp.svg',
    type: 'xrp',
    supportedInterfaces: ['jsonrpc'],
  },
  {
    value: 'apt1',
    label: 'Aptos Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/aptos.svg',
    type: 'aptos',
    supportedInterfaces: ['rest'],
  },
  {
    value: 'btc',
    label: 'Bitcoin Mainnet',
    icon: 'https://info-mainnet.lavanet.xyz/chains/bitcoin.svg',
    type: 'bitcoin',
    supportedInterfaces: ['jsonrpc'],
  },
];

/**
 * Maps chain values to their display labels
 * @param chainValue - The chain value (e.g., "eth1", "near", "arbitrum")
 * @returns The display label (e.g., "Ethereum Mainnet", "NEAR Mainnet", "Arbitrum Mainnet")
 */
export const getChainLabel = (chainValue: string): string => {
  const chain = chains.find(c => c.value === chainValue);
  return chain ? chain.label : chainValue;
};

/**
 * Maps chain labels back to their values
 * @param chainLabel - The chain label (e.g., "Ethereum Mainnet", "NEAR Mainnet")
 * @returns The chain value (e.g., "eth1", "near")
 */
export const getChainValue = (chainLabel: string): string => {
  const chain = chains.find(c => c.label === chainLabel);
  return chain ? chain.value : chainLabel;
};

/**
 * Gets the icon URL for a chain value
 * @param chainValue - The chain value (e.g., "eth1", "near", "arbitrum")
 * @returns The icon URL or empty string if not found
 */
export const getChainIcon = (chainValue: string): string => {
  const chain = chains.find(c => c.value.toLowerCase() === chainValue.toLowerCase());
  return chain ? chain.icon : '';
};
