/* Tooltip texts — ported verbatim from the design prototype
   (page-metrics.jsx TT map). `**bold**` segments are rendered by
   renderTipText in components/gateway/Tip.tsx. */

export const TT: Record<string, string> = {
  errorsCaught:       "Requests that failed but Smart Router **recovered** — via retry, hedge, or failover.\n\n**Without Smart Router, your app would have seen these as errors.**",
  successfulRetries:  "A request failed on the first attempt, so the router **retried it** — on the same endpoint or a different one — and it **succeeded**.\n\nYour app never saw the failure.",
  failoverCatches:    "A request failed on its first-choice upstream and **succeeded after the router switched** to a different upstream.",
  hedgedWins:         "When an upstream was slow, the router fired a **second request in parallel**.\n\nThis counts the times that **hedge came back first** and was returned to your app.",
  staleDetected:      "The router's consistency check caught an upstream serving **data behind the chain head**, and **replaced it with a fresher response**.",
  cacheHitRate:       "Share of cacheable reads **answered straight from cache** instead of a node.\n\nA **direct measurement** (hits ÷ hits + forwarded reads), not an estimate.",
  effectiveSR:        "The success rate your apps **actually experienced**, after the router's retries and failover.",
  reqServed:          "Every request the router handled this window, across all your upstreams — **including cache hits**.",
  rescued:            "Requests that **would have failed on a single node** but the router saved — by retrying, failing over, or a hedge winning.\n\n**Each request is counted once.** The breakdown shows how.",
  cacheLatSaved:      "The **typical time saved** on a cached read: median latency of a node-served read minus median latency of a cache hit.\n\nA per-read median — **not a guarantee** for every cached read.",
  effReadP95:         "Roughly **how much faster reads feel on average** thanks to cache — versus going to a node every time.",
  cacheOffload:       "Share of cacheable reads served **from cache instead of a node** — i.e. **load taken off your infrastructure**.\n\nCached reads never reach an upstream, cutting both calls and cost.",
  availability:       "**Successful synthetic probes** as a share of all probes sent to this upstream.\n\nMeasured **continuously** — not derived from your live traffic.",
  p95:                "**95th-percentile** response time: 95% of requests to this upstream were **faster than this**.",
  blocksBehindChain:  "How many blocks this upstream is **behind the chain head**.\n\nAn upstream many blocks behind may serve **outdated data** to your app.",
  qosScore:           "The router's composite **quality score (0–100)**, blending **availability, latency, and data freshness** into the figure it ranks upstreams on.",
  internalPill:       "A **primary** upstream. The router sends traffic to primary upstreams **first**.",
  fallbackPill:       "A **backup** upstream, used **only when primaries are unavailable** or degraded.",
  removedPill:        "**Temporarily excluded** from traffic. The router detected repeated failures and is waiting for the upstream to recover before re-admitting it.",
  needsAttention:     "A (chain, client) pair is flagged when **failover exceeds 25%**, **success rate drops below 99%**, or **p95 latency exceeds 1.5× the baseline**.",
  routingDecisions:   "Every time the router **chose an upstream, retried, or changed routing state**. Routine selections are included.",
  failoversTriggered: "Requests where the primary upstream failed and the router **automatically retried on another**.",
  primaryChanges:     "Times the router **permanently changed which upstream is first in line** for a chain, based on sustained performance.",
  removedFromRotation:"Upstreams **temporarily pulled from traffic** after repeated failures caught by probing.",
  reads:              "Read requests (`requests_read_total`) — stateless lookups like **eth_call**, **eth_getLogs**, **eth_blockNumber**, **getBalance**.",
  writes:             "Write requests (`requests_write_total`) — state-changing calls like **eth_sendRawTransaction**, **sendTransaction**.",
  batch:              "Batch (multi-call) requests (`requests_batch_total`) — a single payload bundling several calls. Mutually exclusive with reads & writes.",
  addonDebug:         "Debug & trace addon (`requests_debug_trace_total`) — **debug_traceTransaction**, **trace_block**. A **subset** of reads/writes layered on top — not a separate slice, so it overlaps the partition.",
  addonArchive:       "Archive addon (`requests_archive_total`) — queries against **historical state**. A **subset** of reads/writes — not a separate slice, so it overlaps the partition.",
  uncategorized:      "Methods **not yet classified** in the spec catalog — surfaced here for the spec team to triage.",
  categoryPivot:      "Group by **who caused the error**: the router's own systems (**internal**) or an upstream (**external**).",
  retryabilityPivot:  "Group by whether the router **can retry** the error. **Non-retryable** errors need manual intervention.",
  chainPivot:         "Which **blockchain** had the most errors this window.",
  methodPivot:        "Which **RPC method** had the most errors this window.",
  errorCodePivot:     "Break down by **specific error code**. Each code maps to a known failure mode.",
  upstreamPivot:      "Which **upstream** generated the errors. **External** errors go to the upstream that returned them; **internal** errors to the router.",
  upstreamErrors:     "Every error code this upstream returned this window, and how often.\n\n**External errors count against the upstream**; the router **auto-retries the retryable ones**.",
};
